[plugins]
android-application = "com.android.tools.build:gradle:8.4.2"
kotlin-android = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0"

[libraries]
core-ktx = "androidx.core:core-ktx:1.17.0"
appcompat = "androidx.appcompat:appcompat:1.7.0"
material = "com.google.android.material:material:1.12.0"
play-services-location = "com.google.android.gms:play-services-location:21.0.1"
gson = "com.google.code.gson:gson:2.10.1"



